name: Deploy MkDocs Site
#Why This Pipeline is Powerful?
#✅ Reproducible
#Every build runs in a clean environment.
#✅ Automated
#One commit = full site deployed.
#✅ Scalable
#Works for small or large documentation sets.
#✅ Versioned
#Every doc change is tracked via Git history.
#✅ Professional
#Matches workflow of Google, Microsoft etc.


# Triggers this workflow on whenever a change is pushed to anyfile inside docs folder on the main branch.
# Prevents unnecessary deployment and also saves time.
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '**.md'
      - 'mkdocs.yml'
  
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '**.md'


# Runs this job on a fresh Ubuntu VM for every workflow execution
jobs:
  
  preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install mkdocs-material mkdocs-material-extensions pymdown-extensions
      - run: mkdocs build --strict

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
    #The workflow checks out the repository contents so the VM can access "mkdocs.yml", "docs/ folder" and Markdown pages
      - name: Checkout repo
        uses: actions/checkout@v3

    #MkDocs runs on Python, so the VM installs it
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

    #This installs everything required to build the site
      - name: Install MkDocs and Material theme
        run: pip install mkdocs mkdocs-material pymdown-extensions

    #Catches all links that are broken for any reason like missing file or wrong path  
      - name: Validate YAML + check links
        run: mkdocs build --strict

    # Validates the complete yml file for any kind of indentation issue, this saves time and unnecessary use of resources.  
      - name: Validate mkdocs.yml
        run: mkdocs build --config-file mkdocs.yml --strict --verbose


    #MkDocs converts Markdown → HTML
      - name: Build site
        run: mkdocs build

    #The built site is deployed automatically using the community action
    #✅The action pushes HTML files to the gh-pages branch
    #✅ GitHub Pages hosts the updated site
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site 
          
#Troubleshooting the Pipeline
#✅ Build fails
#Check the GitHub Actions log → syntax error in YAML or mkdocs.yml.
#✅ Site not updating
#Check GitHub Pages → ensure mode = GitHub Actions.
#✅ HTML not generated
#Verify mkdocs.yml for missing indentation or bad paths.
#✅ CSS/Layout broken
#Check if mkdocs-material installed correctly.